### ISSUE TITLE
Pictures

### ISSUE THREAD

**Issue by HenrySoftwareStudio** [import-brain/basic_calc_docs#9]
How do I get Nextra to show pictures?

**Comment by import-brain** [comment]
What do you mean? Send a screenshot

You should just be able to embed the pictures with HTML tags.

**Comment by HenrySoftwareStudio** [comment]
Oh, I used markdown tags

**Comment by HenrySoftwareStudio** [comment]
Still, even with absolute path, it was no good
![Screenshot 2021-12-11 182658](https://user-images.githubusercontent.com/86927130/145694745-ba443155-45b5-477c-875d-72a7c3047555.jpg)

**Comment by HenrySoftwareStudio** [comment]
Don't tell me the image has to be on their own line

**Comment by HenrySoftwareStudio** [comment]
Putting the images on their own line doesn't help

**Comment by HenrySoftwareStudio** [comment]
Now back to relative paths

**Comment by HenrySoftwareStudio** [comment]
Got it, what a pain!
